version: "3.9"

services:
  smart-mirror-mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27018:27017" # to prevent conflict with a local mongodb
    networks:
      - smart-mirror-net

  smart-mirror-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - smart-mirror-mongo
    networks:
      - smart-mirror-net

networks:
  smart-mirror-net:
    driver: bridge
