name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

##########
# Tests
##########
  test_and_lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - name: Set up Node.js
        uses: actions/setup-node@v6.2.0
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install

      - name: Run lints
        run: npm run lint --if-present

      - name: Run tests
        run: npm test

##########
# Build and Push
##########
  build_and_push:
    needs: [test_and_lint]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - name: Docker Login
        uses: docker/login-action@v3.7.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Build
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/smart-mirror-api:latest .

      - name: Docker Tag
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/smart-mirror-api:latest \
          ${{ secrets.DOCKERHUB_USERNAME }}/smart-mirror-api:${{ github.sha }}

      - name: Docker Push
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/smart-mirror-api:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/smart-mirror-api:${{ github.sha }}
